### ISSUE TITLE
tornado.application - ERROR - Exception in Future <Future cancelled> after timeout

### ISSUE THREAD

**Issue by xuzhang5788** [Featuretools/Automated-Manual-Comparison#6]
When I ran your notebook Automated Engine Life.ipynb
 cell [in] 5, I got error messages 'ike this:

tornado.application - ERROR - Exception in Future <Future cancelled> after timeout
Traceback (most recent call last):
  File "/home/xuzhang/anaconda3/envs/featuretools/lib/python3.6/site-packages/tornado/gen.py", line 970, in error_callback
    future.result()
concurrent.futures._base.CancelledError
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP local=tcp://127.0.0.1:40210 remote=tcp://127.0.0.1:38483>

Any advice? Thanks

**Comment by WillKoehrsen** [comment]
Hello @xuzhang5788,

Does this prevent the code from running or are these just warnings? In other words, does the feature matrix still get created? 

Also, could you try setting `n_jobs=1` and see if the same messages occur?

**Comment by xuzhang5788** [comment]
@WillKoehrsen ,
Thank you very much for your fast response. After I set n_jobs=1, it works.

**Comment by xuzhang5788** [comment]
Another error message when I ran cell [in] 21.

SpecificationError: Function names must be unique, found multiple named <lambda>

**Comment by WillKoehrsen** [comment]
I'm glad that suggestion worked. 

With regards to your second error, have you edited any of the code?

**Comment by xuzhang5788** [comment]
No. I only changed n_jobs=-1 to n_jobs=1

**Comment by xuzhang5788** [comment]
The error message is very long

feature_matrix, feature_names = ft.dfs(entityset=es, target_entity='engines',

                                       agg_primitives = ['min', 'max', 'mean', 

                                                         'count', 'sum', 'last',

                                                         'skew', 'std', 'trend',

                                                         cid_ce_primitive, number_peaks_primitive, 

                                                         last_location_of_maximum_primititive,

                                                         skewness_primitive, sample_entropy_primitive],

                                       trans_primitives = ['cum_mean', 'cum_sum'],

                                       max_depth = 1, n_jobs = 1, verbose = 1,

                                       chunk_size = 100)

feature_matrix.head()

distributed.comm.tcp - WARNING - Closing dangling stream in <TCP local=tcp://127.0.0.1:46750 remote=tcp://127.0.0.1:40859>

Built 404 features

Elapsed: 00:00 | Remaining: ? | Progress:   0%|          | Calculated: 0/3 chunks

---------------------------------------------------------------------------
SpecificationError                        Traceback (most recent call last)
~/anaconda3/envs/featuretools/lib/python3.6/site-packages/pandas/core/base.py in _aggregate(self, arg, *args, **kwargs)
    489                 try:
--> 490                     result = _agg(arg, _agg_1dim)
    491                 except SpecificationError:

~/anaconda3/envs/featuretools/lib/python3.6/site-packages/pandas/core/base.py in _agg(arg, func)
    440                 for fname, agg_how in compat.iteritems(arg):
--> 441                     result[fname] = func(fname, agg_how)
    442                 return result

~/anaconda3/envs/featuretools/lib/python3.6/site-packages/pandas/core/base.py in _agg_1dim(name, how, subset)
    423                                              "in aggregation")
--> 424                 return colg.aggregate(how, _level=(_level or 0) + 1)
    425 

~/anaconda3/envs/featuretools/lib/python3.6/site-packages/pandas/core/groupby/groupby.py in aggregate(self, func_or_funcs, *args, **kwargs)
   3484             ret = self._aggregate_multiple_funcs(func_or_funcs,
-> 3485                                                  (_level or 0) + 1)
   3486         else:

~/anaconda3/envs/featuretools/lib/python3.6/site-packages/pandas/core/groupby/groupby.py in _aggregate_multiple_funcs(self, arg, _level)
   3549                 raise SpecificationError('Function names must be unique, '
-> 3550                                          'found multiple named %s' % name)
   3551 

SpecificationError: Function names must be unique, found multiple named <lambda>

During handling of the above exception, another exception occurred:

SpecificationError                        Traceback (most recent call last)
<ipython-input-24-1d19b3bc6821> in <module>
      8                                        trans_primitives = ['cum_mean', 'cum_sum'],
      9                                        max_depth = 1, n_jobs = 1, verbose = 1,
---> 10                                        chunk_size = 100)
     11 feature_matrix.head()

~/anaconda3/envs/featuretools/lib/python3.6/site-packages/featuretools/synthesis/dfs.py in dfs(entities, relationships, entityset, target_entity, cutoff_time, instance_ids, agg_primitives, trans_primitives, allowed_paths, max_depth, ignore_entities, ignore_variables, seed_features, drop_contains, drop_exact, where_primitives, max_features, cutoff_time_in_index, save_progress, features_only, training_window, approximate, chunk_size, n_jobs, dask_kwargs, verbose)
    211                                                   n_jobs=n_jobs,
    212                                                   dask_kwargs=dask_kwargs,
--> 213                                                   verbose=verbose)
    214     return feature_matrix, features

~/anaconda3/envs/featuretools/lib/python3.6/site-packages/featuretools/computational_backends/calculate_feature_matrix.py in calculate_feature_matrix(features, entityset, cutoff_time, instance_ids, entities, relationships, cutoff_time_in_index, training_window, approximate, save_progress, verbose, chunk_size, n_jobs, dask_kwargs, profile)
    256                                                  cutoff_df_time_var=cutoff_df_time_var,
    257                                                  target_time=target_time,
--> 258                                                  pass_columns=pass_columns)
    259 
    260     feature_matrix = pd.concat(feature_matrix)

~/anaconda3/envs/featuretools/lib/python3.6/site-packages/featuretools/computational_backends/calculate_feature_matrix.py in linear_calculate_chunks(chunks, features, approximate, training_window, profile, verbose, save_progress, entityset, no_unapproximated_aggs, cutoff_df_time_var, target_time, pass_columns)
    518                                           cutoff_df_time_var,
    519                                           target_time, pass_columns,
--> 520                                           backend=backend)
    521         feature_matrix.append(_feature_matrix)
    522         # Do a manual garbage collection in case objects from calculate_chunk

~/anaconda3/envs/featuretools/lib/python3.6/site-packages/featuretools/computational_backends/calculate_feature_matrix.py in calculate_chunk(chunk, features, approximate, training_window, profile, verbose, save_progress, no_unapproximated_aggs, cutoff_df_time_var, target_time, pass_columns, backend, entityset)
    340                                            ids,
    341                                            precalculated_features=precalculated_features,
--> 342                                            training_window=window)
    343 
    344             id_name = _feature_matrix.index.name

~/anaconda3/envs/featuretools/lib/python3.6/site-packages/featuretools/computational_backends/utils.py in wrapped(*args, **kwargs)
     32         def wrapped(*args, **kwargs):
     33             if save_progress is None:
---> 34                 r = method(*args, **kwargs)
     35             else:
     36                 time = args[0].to_pydatetime()

~/anaconda3/envs/featuretools/lib/python3.6/site-packages/featuretools/computational_backends/calculate_feature_matrix.py in calc_results(time_last, ids, precalculated_features, training_window)
    314                                                     precalculated_features=precalculated_features,
    315                                                     ignored=all_approx_feature_set,
--> 316                                                     profile=profile)
    317             return matrix
    318 

~/anaconda3/envs/featuretools/lib/python3.6/site-packages/featuretools/computational_backends/pandas_backend.py in calculate_all_features(self, instance_ids, time_last, training_window, profile, precalculated_features, ignored, verbose)
    194 
    195                     handler = self._feature_type_handler(test_feature)
--> 196                     result_frame = handler(group, input_frames)
    197 
    198                     output_frames_type = self.feature_tree.output_frames_type(test_feature)

~/anaconda3/envs/featuretools/lib/python3.6/site-packages/featuretools/computational_backends/pandas_backend.py in _calculate_agg_features(self, features, entity_frames)
    453             # work)
    454             to_merge = base_frame.groupby(base_frame[groupby_var],
--> 455                                           observed=True, sort=False).agg(to_agg)
    456             # rename columns to the correct feature names
    457             to_merge.columns = [agg_rename["-".join(x)] for x in to_merge.columns.ravel()]

~/anaconda3/envs/featuretools/lib/python3.6/site-packages/pandas/core/groupby/groupby.py in aggregate(self, arg, *args, **kwargs)
   4654         axis=''))
   4655     def aggregate(self, arg, *args, **kwargs):
-> 4656         return super(DataFrameGroupBy, self).aggregate(arg, *args, **kwargs)
   4657 
   4658     agg = aggregate

~/anaconda3/envs/featuretools/lib/python3.6/site-packages/pandas/core/groupby/groupby.py in aggregate(self, arg, *args, **kwargs)
   4085 
   4086         _level = kwargs.pop('_level', None)
-> 4087         result, how = self._aggregate(arg, _level=_level, *args, **kwargs)
   4088         if how is None:
   4089             return result

~/anaconda3/envs/featuretools/lib/python3.6/site-packages/pandas/core/base.py in _aggregate(self, arg, *args, **kwargs)
    493                     # we are aggregating expecting all 1d-returns
    494                     # but we have 2d
--> 495                     result = _agg(arg, _agg_2dim)
    496 
    497             # combine results

~/anaconda3/envs/featuretools/lib/python3.6/site-packages/pandas/core/base.py in _agg(arg, func)
    439                 result = compat.OrderedDict()
    440                 for fname, agg_how in compat.iteritems(arg):
--> 441                     result[fname] = func(fname, agg_how)
    442                 return result
    443 

~/anaconda3/envs/featuretools/lib/python3.6/site-packages/pandas/core/base.py in _agg_2dim(name, how)
    430                 colg = self._gotitem(self._selection, ndim=2,
    431                                      subset=obj)
--> 432                 return colg.aggregate(how, _level=None)
    433 
    434             def _agg(arg, func):

~/anaconda3/envs/featuretools/lib/python3.6/site-packages/pandas/core/groupby/groupby.py in aggregate(self, arg, *args, **kwargs)
   4654         axis=''))
   4655     def aggregate(self, arg, *args, **kwargs):
-> 4656         return super(DataFrameGroupBy, self).aggregate(arg, *args, **kwargs)
   4657 
   4658     agg = aggregate

~/anaconda3/envs/featuretools/lib/python3.6/site-packages/pandas/core/groupby/groupby.py in aggregate(self, arg, *args, **kwargs)
   4085 
   4086         _level = kwargs.pop('_level', None)
-> 4087         result, how = self._aggregate(arg, _level=_level, *args, **kwargs)
   4088         if how is None:
   4089             return result

~/anaconda3/envs/featuretools/lib/python3.6/site-packages/pandas/core/base.py in _aggregate(self, arg, *args, **kwargs)
    549             return self._aggregate_multiple_funcs(arg,
    550                                                   _level=_level,
--> 551                                                   _axis=_axis), None
    552         else:
    553             result = None

~/anaconda3/envs/featuretools/lib/python3.6/site-packages/pandas/core/base.py in _aggregate_multiple_funcs(self, arg, _level, _axis)
    595                     colg = self._gotitem(col, ndim=1,
    596                                          subset=obj.iloc[:, index])
--> 597                     results.append(colg.aggregate(arg))
    598                     keys.append(col)
    599                 except (TypeError, DataError):

~/anaconda3/envs/featuretools/lib/python3.6/site-packages/pandas/core/groupby/groupby.py in aggregate(self, func_or_funcs, *args, **kwargs)
   3483             # but not the class list / tuple itself.
   3484             ret = self._aggregate_multiple_funcs(func_or_funcs,
-> 3485                                                  (_level or 0) + 1)
   3486         else:
   3487             cyfunc = self._is_cython_func(func_or_funcs)

~/anaconda3/envs/featuretools/lib/python3.6/site-packages/pandas/core/groupby/groupby.py in _aggregate_multiple_funcs(self, arg, _level)
   3548             if name in results:
   3549                 raise SpecificationError('Function names must be unique, '
-> 3550                                          'found multiple named %s' % name)
   3551 
   3552             # reset the cache so that we

SpecificationError: Function names must be unique, found multiple named <lambda>

**Comment by kmax12** [comment]
@xuzhang5788  we just fixed this issue in https://github.com/Featuretools/featuretools/pull/321 of the Featuretools library

Can you try to install that branch of featuretools and test if it works? you can do with the following command

```
pip install -e git://github.com/featuretools/featuretools.git@primitive-naming#egg=featuretools
```

Thanks for the help on this!

**Comment by WillKoehrsen** [comment]
@kmax12 I can confirm installing that branch of Featuretools fixed the issue for me. Thanks! 
However, I think it's prudent to also update the notebook to give each function a unique name.

**Comment by WillKoehrsen** [comment]
@kmax12 I tried renaming the `lambda` functions as shown below (using `.__name__`) but still got errors when not using your fix. The fix you suggested does work, but I'm curious why the below approach does not solve the issue? 

![Renaming lambda functions](https://user-images.githubusercontent.com/17484616/48631995-6ccb8700-e985-11e8-9d74-da6c00db631b.png)

**Comment by WillKoehrsen** [comment]
@xuzhang5788 I created a new version of the notebook that works even without @kmax12's fix. [Updated Notebook](https://github.com/Featuretools/Automated-Manual-Comparison/blob/master/Engine%20Life/notebooks/Automated%20Engine%20Life.ipynb). 

You can either use the fix or use the updated notebook!

**Comment by xuzhang5788** [comment]
@WillKoehrsen @kmax12 
I installed that branch of featuretools, and ran the old notebook, I got a lot of "red outputs". I am not sure if they are all matter. 

This is the screenshots links. Please have a look. Thanks.
https://screenshots.firefox.com/iiqur9TUpvDBUGzI/localhost

**Comment by WillKoehrsen** [comment]
Do these prevent the notebook from running?

**Comment by xuzhang5788** [comment]
No.

**Comment by WillKoehrsen** [comment]
I'm going to close the issue if the warnings don't prevent the `feature_matrix` from being created. Feel free to re-open if you run into problems. We also get some Tornado warnings when running `dfs` especially when `n_jobs>1` but they do not prevent the calculations from completing.
